### ISSUE TITLE
Assessment scripts missing

### ISSUE THREAD

**Issue by Hofphi** [Functional-Genomics/CrossSpeciesIntegration#1]
Hi,

first of all I would like to thank you for this great benchmarking pipeline!! I'd really liked to test this with my own datasets, however I have noticed that some scripts are missing to run the integration-assessment.

The following scripts are missing:
```
sccaf_assessment_metadata.py
sccaf_projection_multiple_species.py
kbet_multiple_species.R
scIB_metrics.py
scIB_trajectory.py
```

Would you be able to provide those scripts?

Furthermore, I noticed that the implementation of a SAMap integration-workflow is missing but you do report results in your preprint. Is there a reason why this implementation is missing?

Looking forward to hear from you.

Best,
Philipp

**Comment by YY-SONG0718** [comment]
Hi Philipp,

The scripts have been provided along with updates.

Kind regards,
Yuyao
