### ISSUE TITLE
Using scANVI for Cross-Species Integration

### ISSUE THREAD

**Issue by VishD17** [Functional-Genomics/CrossSpeciesIntegration#7]
Hello,

Thank you for this great tool! We had a few questions regarding scANVI and its utilization as a valid cross-species integration method.

1. It has been established that scANVI is informed by cell labels during integration, but of what nature are these labels? Are they used to distinguish cells within or across species?
2. If the labels being passed are used to distinguish cells across species, would that not artificially inflate integration scores as the integration is supervised?

Thank you for the help!

**Comment by YY-SONG0718** [comment]
hello,

Thanks for your message and thoughts about scANVI.

1. The labels are used to distinguish different cell types within each species, such as muscle, neuron, epithelial.. etc. When integrating between species, the same cell type label shared between them will be utilized to help with the integration. The idea is to provide coerce-level shared cell type labels between species, integrate them, and then perform further clustering on integrated data to identify more granular populations shared, or unique, between species.

2. It is indeed a semi-supervised method, so will have higher scores for label-dependent metrics. However, there are also label-independent metrics. Please refer to supplementary methods in the paper.

**Comment by VishD17** [comment]
Thank you for the timely reply—this was extremely helpful!
